# Generated by Django 4.2.7 on 2023-11-09 12:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_preco_precos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='equipe', variations={'thumb': {'crop': True, 'height': 20, 'width': 20}}, verbose_name='Imagem'),
        ),
    ]
