# Generated by Django 4.2.7 on 2023-11-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='criado',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualização'),
        ),
    ]
